x-common-svc: &common
  env_file: "../../.env"
services:
  pg:
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin4:
    <<: *common
    image: dpage/pgadmin4:8.13.0
    ports:
      - 5550:80
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json:ro
  redis:
    image: redis:7.4.7-alpine3.21
    ports:
      - "5551:6379"
  srh:
    image: hiett/serverless-redis-http:0.0.10
    ports:
      - "5552:80"
    environment:
      SRH_MODE: env
      SRH_TOKEN: dev_token
      SRH_CONNECTION_STRING: "redis://redis:6379"
  redisinsight:
    image: redis/redisinsight:2.70
    ports:
      - "5553:5540"
    depends_on:
      - redis
    volumes:
      - redisinsight:/data
volumes:
  pgdata:
  pgadmin:
  redisinsight:
