import React from "react";
import { CircularProgress, Typography } from "@mui/material";
import PersonIcon from "@mui/icons-material/Person";
import Image from "next/image";

import Link from "@/components/Link/Link";
import { ROUTES } from "@/utils/routes";
import { VerticalStack } from "@/components/Layout/Containers";
import Button from "@/components/Button/Button";
import { Divider } from "@/components/Layout/Dividers";
import { AuthType } from "@/components/AuthForm/AuthForm";
import { useAppSnackbar } from "@/utils/snackbar";
import { trpc } from "@/trpc";
import useUser from "@/trpc/hooks/useUser";
import { useRouter } from "next/router";

type WrapperProps = {
  authType: AuthType;
  disabled: boolean;
  children: React.ReactNode;
  onSuccess?: () => void;
};

export const oauthDoneStatus = {
  success: "success",
  error: "error",
  new_user: "new_user",
} as const;

export type OauthDoneStatus = keyof typeof oauthDoneStatus | "";

export const OAUTH_DONE = "oauth_done";

export type OauthPopupMessage = {
  type: typeof OAUTH_DONE;
  status: OauthDoneStatus;
};

const isOauthPopupMessage = (
  event: MessageEvent
): event is MessageEvent<OauthPopupMessage> => {
  const message = event.data;
  if (
    event.origin !== window.location.origin ||
    !message ||
    typeof message !== "object"
  ) {
    return false;
  }
  const assertedMessage = message as OauthPopupMessage;
  return (
    assertedMessage.type === OAUTH_DONE &&
    typeof assertedMessage.status === "string"
  );
};

export const AuthWrapper = (props: WrapperProps) => {
  const isLogin = props.authType === "login";

  const { addAppSnackbar } = useAppSnackbar();
  const utils = trpc.useUtils();

  const oauthPopupRef = React.useRef<Window | null>(null);

  const openOauthPopup = () => {
    const popupWidth = 520;
    const popupHeight = 650;

    const currentScreenLeft = window.screenLeft ?? window.screenX ?? 0;
    const currentScreenTop = window.screenTop ?? window.screenY ?? 0;
    const screenWidth = window.outerWidth ?? window.innerWidth;
    const screenHeight = window.outerHeight ?? window.innerHeight;

    const left = Math.round(currentScreenLeft + (screenWidth - popupWidth) / 2);
    const top = Math.round(currentScreenTop + (screenHeight - popupHeight) / 2);

    const features = [
      "popup=yes",
      `width=${popupWidth}`,
      `height=${popupHeight}`,
      `left=${left}`,
      `top=${top}`,
    ].join(",");

    const popup = window.open(ROUTES.oauthStarting, "oauth_google", features);
    oauthPopupRef.current = popup;
  };

  const googleLoginMutation = trpc.auth.googleLogin.useMutation({
    async onSuccess(data) {
      if (!data.url) {
        addAppSnackbar({ message: "Something went wrong.", variant: "error" });
        return;
      }

      const popup = oauthPopupRef.current;

      if (!popup) {
        window.location.href = data.url;
        return;
      }
      try {
        popup.focus();
        popup.location.href = data.url;
      } catch (err) {
        window.location.href = data.url;
        return;
      }

      let onMessage: ((e: MessageEvent) => Promise<void>) | null = null;
      let closedPopupInterval: ReturnType<typeof setInterval> | null = null;

      const cleanup = () => {
        if (onMessage) window.removeEventListener("message", onMessage);
        if (closedPopupInterval) window.clearInterval(closedPopupInterval);
        oauthPopupRef.current = null;
      };

      const handleSuccess = () => {
        utils.auth.user.invalidate();
        props.onSuccess?.();
      };

      await new Promise<void>((resolve) => {
        onMessage = async (event: MessageEvent) => {
          if (!isOauthPopupMessage(event)) return;

          try {
            popup.close();
          } catch (e) {}

          if (event.data.status === "error") {
            addAppSnackbar({
              message: "Something went wrong.",
              variant: "error",
            });
            cleanup();
            resolve();
            return;
          }

          if (event.data.status === "new_user") {
            addAppSnackbar({
              message:
                "Welcome. Your username will be autogenerated. You can change it in your profile page.",
              variant: "info",
              durationMs: 0,
            });
          }

          cleanup();
          handleSuccess();
          resolve();
        };
        closedPopupInterval = setInterval(() => {
          if (popup.closed) {
            cleanup();
            resolve();
          }
        }, 500);
        window.addEventListener("message", onMessage);
      });
    },
    onError() {
      addAppSnackbar({ message: "Something went wrong.", variant: "error" });
      oauthPopupRef.current = null;
    },
  });
  const guestLoginMutation = trpc.auth.loginAnonymous.useMutation({
    onSuccess() {
      utils.auth.user.invalidate();
      props.onSuccess?.();
    },
  });

  const onGoogleClick = async () => {
    openOauthPopup();
    googleLoginMutation.mutate();
  };

  const onGuestClick = () => {
    guestLoginMutation.mutate();
  };

  const isDisabled =
    guestLoginMutation.isPending ||
    googleLoginMutation.isPending ||
    props.disabled;

  return (
    <>
      <VerticalStack>
        <Button
          isLoading={googleLoginMutation.isPending}
          disabled={isDisabled}
          color="inherit"
          variant="outlined"
          fullWidth
          size="large"
          onClick={onGoogleClick}
          startIcon={
            <Image
              src="/icons/google.svg"
              alt="google-icon"
              width={22}
              height={22}
              priority
            />
          }
        >
          {isLogin ? "Log in" : "Sign up"} with Google
        </Button>
        <Button
          isLoading={guestLoginMutation.isPending}
          disabled={isDisabled}
          color="inherit"
          variant="outlined"
          fullWidth
          size="large"
          onClick={onGuestClick}
          startIcon={<PersonIcon />}
        >
          Continue as guest
        </Button>
      </VerticalStack>
      <Divider className="my-4">
        or {isLogin ? "log in with your credentials" : "create an account"}
      </Divider>
      {props.children}
      <TermsLabel />
    </>
  );
};

export const TermsLabel = () => {
  return (
    <Typography variant="subtitle2" className="mt-4">
      <span>
        By continuing, you agree to the{" "}
        <Link target="_blank" href={ROUTES.terms}>
          Terms and Conditions
        </Link>{" "}
        and{" "}
        <Link target="_blank" href={ROUTES.privacyPolicy}>
          Privacy Policy
        </Link>
      </span>
    </Typography>
  );
};

type AuthPageWrapperProps = {
  children: React.ReactNode;
};

export const AuthPageWrapper = (props: AuthPageWrapperProps) => {
  const user = useUser();
  const router = useRouter();

  if (user.data?.user?.id) {
    router.replace(ROUTES.private_myProfile);
    return;
  }

  return (
    <div className="flex-1 flex justify-center items-center">
      {user.isPending ? (
        <CircularProgress />
      ) : (
        <div className="max-w-[600px] w-full">{props.children}</div>
      )}
    </div>
  );
};
