name: Migrate DB

on:
  push:
    branches:
      - master
    paths:
      - "drizzle/**"
  workflow_dispatch: {}

concurrency:
  group: migrate-prod
  cancel-in-progress: false

jobs:
  migrate:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5.0.0
      - name: Setup node
        uses: actions/setup-node@v6.0.0
        with:
          node-version: "22.17.1"
      - name: Cache node_modules
        id: nm-cache
        uses: actions/cache@v4.3.0
        with:
          path: node_modules
          key: ${{ runner.os }}-node-22.17.1-${{ hashFiles('package-lock.json') }}
      - name: Install deps
        if: steps.nm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run DB migrations
        run: npm run db:m-prod
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_URL_UNPOOLED: ${{ secrets.DATABASE_URL_UNPOOLED }}
