name: Sync to public repo's master branch

# Overwriting the whole master branch of the public repo with the private's master branch
# Private repo receives all commits and just syncs with the public repo
# The reason is to keep CI logs private from accidentally exposing any secret variables/etc
# Just better security in general

on:
  push:
    branches: [master]
  workflow_dispatch: {}

concurrency:
  group: sync-to-public
  cancel-in-progress: false

jobs:
  sync_to_public:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push master to public (overwrite)
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_PUSH_TOKEN }}
          PUBLIC_REPO: ${{ secrets.PUBLIC_REPO_NAME }}
        run: |
          set -euo pipefail

          git push --force "https://x-access-token:${TOKEN}@github.com/${PUBLIC_REPO}.git" HEAD:master
